---

- name: Add graphite user
  user: name=graphite
  tags: graphite
  sudo: true

- copy: src=graphite-requirements.txt dest=/tmp/requirements.txt
  tags: graphite
  sudo: true

- name: Install Graphite Dependencies
  apt: "pkg={{ item }} state=present"
  with_items:
    - build-essential
    - python-pip
    - python-dev
    - libcairo2
    - libcairo2-dev
    - python-cairo
    - sqlite
  tags: graphite
  sudo: true

- name: Create PIP requirements file
  copy: src=graphite-requirements.txt dest=/tmp/requirements.txt
  tags: graphite
  sudo: true

- name: Install uwsgi from PIP
  pip: name=uwsgi
  tags: graphite
  sudo: true

- name: Install Graphite from PIP
  pip: requirements=/tmp/requirements.txt
  environment:
    PYTHONPATH: "/opt/graphite/lib:/opt/graphite/webapp"
  tags: graphite
  sudo: true

- name: Configure carbon cache
  copy: src=carbon.conf dest=/opt/graphite/conf/carbon.conf mode=0644
  tags: graphite
  sudo: true

- name: Configure carbon storage schema
  copy: src=storage-schemas.conf dest=/opt/graphite/conf/storage-schemas.conf mode=0644
  tags: graphite
  sudo: true

- name: Configure carbon storage aggregation
  copy: src=storage-aggregation.conf dest=/opt/graphite/conf/storage-aggregation.conf mode=0644
  tags: graphite
  sudo: true

- name: Configure carbon upstart script
  copy: src=carbon-cache.upstart dest=/etc/init/carbon-cache.conf mode=0755
  tags: graphite
  sudo: true

- name: Configure graphite upstart script
  copy: src=graphite.upstart dest=/etc/init/graphite.conf mode=0755
  tags: graphite
  sudo: true

- name: Configure Graphite webapp
  copy: src=graphite-localsettings.py dest=/opt/graphite/webapp/graphite/local_settings.py mode=0644
  tags: graphite
  sudo: true

- name: Configure graphite.wsgi
  copy: src=graphite.wsgi dest=/opt/graphite/conf/graphite.wsgi mode=0644
  tags: graphite
  sudo: true

- name: Setup sqlite DB
  command: /usr/bin/python manage.py syncdb --noinput chdir=/opt/graphite/webapp/graphite 
   creates=/opt/graphite/storage/graphite.db
  tags: graphite
  sudo: true

- name: Get directory permissions
  stat: path=/opt/graphite
  register: permissions
  tags: graphite
  sudo: true

- name: Set file permissions
  command: /bin/chown -R graphite:graphite /opt/graphite
  tags: graphite
  sudo: true

- name: Set file permissions (TEMP)
  command: /bin/chmod -R 777 /opt/graphite
  tags: graphite
  sudo: true

- name: Start carbon cache
  service: name=carbon-cache state=running enabled=yes
  tags: graphite
  sudo: true

- name: Start graphite
  service: name=graphite state=running enabled=yes
  tags: graphite
  sudo: true
