%YAML 1.2
---
- name: ensure required packages are installed for Java 7
  apt: name=$item state=latest update_cache=yes
  with_items:
    - python-software-properties
    - python-pycurl
  sudo: yes
  tags: java
 
- name: Add Java repository to sources
  action: apt_repository repo='ppa:webupd8team/java'
  sudo: yes
  tags: java
 
- name: Autoaccept license for Java
  action: shell echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
  sudo: yes
  tags: java
 
- name: Update APT package cache
  action: apt update_cache=yes
  sudo: yes
  tags: java
 
- name: Install Java 7
  action: apt pkg=oracle-java7-installer state=latest install_recommends=yes
  sudo: yes
  tags: java
 
- name: Set Java 7 Env
  action: apt pkg=oracle-java7-set-default state=latest install_recommends=yes
  sudo: yes
  tags: java

- name: Download Riemann as .deb
  get_url: url=http://aphyr.com/riemann/riemann_0.2.4_all.deb dest=/root/riemann.deb
  sudo: yes
  tags: riemann

- name: Install Riemann
  command: dpkg -i /root/riemann.deb
  sudo: yes
  tags: riemann

- name: Remove old initv script
  file: path=/etc/init.d/riemann state=absent
  tags: riemann
  sudo: yes

- name: Configure Riemann upstart script
  template: src=riemann.upstart.j2 dest=/etc/init/riemann.conf
  tags: riemann
  sudo: yes

- name: Clone Baseline
  git: repo=https://github.com/joestanton/baseline dest=/opt/baseline
  tags: riemann
  sudo: yes

- name: Remove default riemann config
  file: path=/etc/riemann/riemann.config state=absent
  tags: riemann
  sudo: yes

- name: Symlink config
  file: state=link dest=/etc/riemann/riemann.config src=/opt/baseline/baseline.config
  tags: riemann
  sudo: yes

- name: Set log permissions
  file: path=/var/log/riemann/riemann.log mode=0777 state=touch
  sudo: yes
  tags: riemann

- name: restart riemann
  service: name=riemann
           state=reloaded
           enabled=yes
  tags: riemann
  sudo: yes
