%YAML 1.2
---
- name: Set permissions
  file: path=/opt/ mode=0777
  sudo: yes
  tags: api

- name: Set log permissions
  file: path=/var/log/baseline-api.log mode=0777 state=touch
  sudo: yes
  tags: api

- name: Clone baseline-api Repo
  git: repo=https://github.com/joestanton/baseline-api
       dest=/opt/baseline-api
  tags: api

- name: Configuring upstart
  template: src=baseline-api.upstart.j2 dest=/etc/init/baseline-api.conf mode=0755
  sudo: yes
  tags: api

- name: Install Bundler
  shell: gem install bundler
  sudo: yes
  tags: api

- name: Bundle Install
  shell: bundle install
       chdir=/opt/baseline-api
  sudo: yes
  tags: api

- name: Creating Database
  shell: rake db:create RAILS_ENV=production
       chdir=/opt/baseline-api
  sudo: yes
  tags: api

- name: Running Migrations
  shell: rake db:migrate RAILS_ENV=production
       chdir=/opt/baseline-api
  sudo: yes
  tags: api

- name: Restart API
  service: name=baseline-api state=restarted
  sudo: yes
  tags: api
