%YAML 1.2
---
- name: Install Dependencies
  apt: pkg={{item}}
  with_items:
    - python-software-properties
    - software-properties-common
    - python-pycurl
  sudo: yes
  tags: nginx

- name: Add Nginx Repository
  apt_repository: repo=ppa:nginx/stable
  sudo: yes
  tags: nginx

- name: Install Nginx
  apt: pkg=nginx-full
  sudo: yes
  tags: nginx

- name: Create nginx user
  user: name=nginx
  sudo: yes
  tags: nginx

- name: Configure Nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/default.conf owner=nginx group=nginx mode=0644
  sudo: yes
  tags: nginx

- name: Set /var/www/ permissions
  file: path=/var/www/ mode=0777 state=directory
  sudo: yes
  tags: nginx

- name: Start Nginx
  action: service name=nginx state=restarted
  sudo: yes
  tags: nginx
